### ISSUE TITLE
Remove Ensembles completely

### ISSUE THREAD

**Issue by mattben** [PCMDI/cmip6-publication-site#12]
Remove the ensemble completely. 
lets start with removing it as an option on the form. I'm afraid if we remove the model, it will be needed again some day.

**Comment by mattben** [comment]
remove ensemble from the form, and always submit a 1. This is never shown, and may be asked for in the future.

**Comment by mattben** [comment]
@James-Crean is this in one of the last commits?

**Comment by James-Crean** [comment]
This is next up to do

**Comment by James-Crean** [comment]
Fixed in 7237d45.
