### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by mattben** [PCMDI/cmip6-publication-site#2]
Can not be required

**Comment by James-Crean** [comment]
I believe it was previously agreed that the DOI should be required if the article was published, and be optional if the article was submitted, accepted, or otherwise. Is this no longer the case?

**Comment by mattben** [comment]
... I guess I can just keep entering 'none'

**Comment by James-Crean** [comment]
I can set it to never be required, I just wanted to make sure that you knew it was currently only required when the status was "published"

**Comment by mattben** [comment]
Lets leave it as is then
