### ISSUE TITLE
Editing Publication

### ISSUE THREAD

**Issue by mattben** [PCMDI/cmip6-publication-site#28]
If a project that has no attributes is selected, this div should be hidden.

![screen shot 2016-07-28 at 7 07 33 am](https://cloud.githubusercontent.com/assets/438922/17215534/05580ede-5492-11e6-88bb-1c491af2537a.png)

**Comment by James-Crean** [comment]
This should be fixed in 7237d45. When was the last time the site pulled from git?

**Comment by mattben** [comment]
@James-Crean Just pulled, migrated, and collected static. restarted httpd ~and its still there~. Deleted cache and it worked! thank you
https://cmip-publications.llnl.gov
