### ISSUE TITLE
authors field

### ISSUE THREAD

**Issue by mattben** [PCMDI/cmip6-publication-site#29]
now that I've entered a few publications, I see i'm in the database three times and the quick text is not finding me as an option.

**M. B.**
![screen shot 2016-07-28 at 7 20 23 am](https://cloud.githubusercontent.com/assets/438922/17216030/d4b9043e-5493-11e6-8b7c-8820156e2579.png)

**Harris**
![screen shot 2016-07-28 at 7 20 35 am](https://cloud.githubusercontent.com/assets/438922/17216045/e2102446-5493-11e6-99ec-6af186f8e0d5.png)

**Comment by mattben** [comment]
I just pulled the change to server, it still does not find me _M. B. Harris_. I'm in the DB 3 times.

![screen shot 2016-07-28 at 8 47 20 am](https://cloud.githubusercontent.com/assets/438922/17219365/fa78c8c4-549f-11e6-841c-8aba8383906a.png)

**Comment by James-Crean** [comment]
Clear yur cache bruh.
