### ISSUE TITLE
Problem submitting AIMS publication

### ISSUE THREAD

**Issue by chaosphere2112** [PCMDI/cmip6-publication-site#43]
Tanya ran into an issue submitting an AIMS publication (DOI: 10.2172/1253685) as a Technical Report. No error message was present on the screen, but I dug into the inspector and it looks like it was a missing required field (though it looked like they had all been filled out).

**Comment by mattben** [comment]
What is the report Number?

**Comment by mattben** [comment]
fixed: https://github.com/PCMDI/cmip6-publication-site/commit/d291f244b6706f10b8b9a9fde3c19cfeeaffebde
